baseURL: https://tondauer.art/
theme:
  - custom
  - bootstrap4-blog
DefaultContentLanguage: en
paginate: 5

copyright: "[CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/deed.en) Copyright © 2021 by Benjamin Geer"

permalinks:
  posts: "/:year/:month/:slug/"
  page: "/:slug/"
  /: "/:slug/"

languages:
  en:
    languageCode: en
    contentDir: content/en
    languageName: English
    title: Tondauer
    weight: 1
    params:
      description: open music editions
      sharingicons: false
    menu:
      navbar:
        - name: "About This Project"
          url: "/about-this-project/"
          weight: 1
        - name: "Source Code"
          url: "https://github.com/benjamingeer/Tondauer"
          weight: 2
  fr:
    languageCode: fr
    contentDir: content/fr
    languageName: Français
    title: Tondauer
    weight: 1
    params:
      description: éditions musicales libres
      sharingicons: false
    menu:
      navbar:
        - name: "À propos de ce projet"
          url: "/a-propos-de-ce-projet/"
          weight: 1
        - name: "Code source"
          url: "https://github.com/benjamingeer/Tondauer"
          weight: 2
          
params:
  date_format: "2006-01-02"

markup:
  goldmark:
    renderer:
      unsafe: true

